#!/bin/sh

umask 002
directory=${0%/*}
cd $directory
if [ -z "$1" ]; then
    config=config.ini
else
    config="$1"
fi

ARGS='config=sys.argv[1]'
[ -f .consumerc ] && . ./consumerc
[ -n "$EXTRA_ARGS" ] && ARGS="$ARGS, $EXTRA_ARGS"

. bin/activate
exec python -c "
import sys
sys.argv[0] = 'consume'
from spamfilter.consume import SpamConsumer
SpamConsumer($ARGS).process(sys.stdin)
sys.exit(0)" "$config"
