#!/bin/sh

umask 002
directory=${0%/*}
cd $directory
. bin/activate
exec python -c '
import sys
from spamfilter.greylist import GreylistPolicy
GreylistPolicy(config=sys.argv[1]).process()
sys.exit(0)' config.ini
