#!/bin/sh

umask 002
directory=${0%/*}
cd $directory
if [ -z "$1" ]; then
    config=config.ini
else
    config="$1"
fi

ARGS='config=sys.argv[1]'
[ -f .honeypotrc ] && . ./honeypotrc
[ -n "$EXTRA_ARGS" ] && ARGS="$ARGS, $EXTRA_ARGS"

. bin/activate
python -c "
import sys
sys.argv[0] = 'honeypot'
from spamfilter.honeypot import HoneyPot
HoneyPot($ARGS).run()" "$config"
