#!/bin/sh

umask 002
directory=${0%/*}
cd $directory
if [ -z "$1" ]; then
    config=config.ini
else
    config="$1"
fi

. bin/activate
exec python -c '
import sys
sys.argv[0] = "policy"
from spamfilter.policy import PolicyManager
PolicyManager(config=sys.argv[1]).process()
sys.exit(0)' "$config"
