#!/bin/sh

umask 002
directory=${0%/*}
cd $directory
. bin/activate
exec python -c '
import sys
from spamfilter.relay import Relay
Relay(config=sys.argv[1], host=sys.argv[2]).processMessage()
sys.exit(0)' config.ini $1
