#!/bin/sh

umask 002
directory=${0%/*}
cd $directory
if [ -z "$2" ]; then
    config=config.ini
else
    config="$1"
    shift
fi

ARGS='config=sys.argv[1]'
[ -f .report_spamrc ] && . ./report_spamrc
[ -n "$EXTRA_ARGS" ] && ARGS="$ARGS, $EXTRA_ARGS"

. bin/activate
exec python -c "
import sys
sys.argv[0] = 'consume'
from spamfilter.consume import SpamConsumer
SpamConsumer($ARGS).report_spam(sys.argv[2])
sys.exit(0)" "$config" "$1"
