#!/bin/sh

umask 002
directory=${0%/*}
cd $directory
. bin/activate
exec python -c '
import sys
sys.argv[0] = "report"
from spamfilter.report import ReportGenerator
ReportGenerator(config=sys.argv[1]).report()
sys.exit(0)' config.ini
