#!/bin/sh

umask 002
directory=${0%/*}
cd $directory
if [ -z "$2" ]; then
    config=config.ini
else
    config="$1"
    shift
fi

. bin/activate
exec python -c '
import sys
sys.argv[0] = "consume"
from spamfilter.consume import SpamConsumer
SpamConsumer(config=sys.argv[1]).reportSpam(sys.argv[2])
sys.exit(0)' "$config" "$1"
