#!/bin/sh

umask 002
directory=${0%/*}
cd $directory
. bin/activate
exec python -c '
import sys
from spamfilter.spamcheck import SpamCheck
SpamCheck(sys.argv[1]).processMessage()
sys.exit(0)' config.ini
